services:
  web:
    image: python:3.11-slim
    container_name: user_platform
    working_dir: /app
    volumes:
      # Mounts the user_platform directory into the container's /app directory
      - ./user_platform:/app
    ports:
      # Maps your local port 16999 to the container's port 16999
      - "16888:16888"
    environment:
      - FERNET_KEY="6gIX0NVO-B1waQNCrEnikAJe8QRCXWfO3MQKr_toim0="
    env_file:
      - ./user_platform/.env
    # Add this section to connect to the external network
    networks:
      - mysql_default
      - vault_default
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt && python run.py"
    restart: unless-stopped
# Define the external network
networks:
  mysql_default:
    external: true
  vault_default:
    external: true
