services:
  flask-login:
    image: python:3.11-slim
    container_name: foti_platform
    working_dir: /python
    volumes:
      - ./python:/python
    ports:
      - "18999:18999"
    environment:
      FORTI_PLATFORM_API_BASE: http://172.26.1.176:18999
      FORTI_USE_REAL_GITLAB: 1
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python run.py"

